# Generated by Django 3.2.5 on 2021-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.PositiveIntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('pressure', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
